[package]
name = "itconfig"
version = "1.0.0"
authors = ["Dmitriy Pleshevskiy <dmitriy@ideascup.me>"]
description = "Easy build a configs from environment variables and use it in globally."
categories = ["config", "web-programming"]
keywords = ["config", "env", "configuration", "environment", "macro"]
edition = "2018"
license = "MIT"
repository = "https://github.com/icetemple/itconfig-rs"
homepage = "https://github.com/icetemple/itconfig-rs"
documentation = "https://docs.rs/itconfig"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
failure = { version = "0.1.7", features = ["derive"]}
serde_json = { version = "1.0.44", optional = true }
itconfig-macro = { version = "1.0", path = "../itconfig-macro", optional = true }

[dev-dependencies]
lazy_static = "1.4.0"

[features]
default = ["primitives"]

macro = ["itconfig-macro"]

array = ["serde_json"]

primitives = ["numbers", "bool"]
numbers = ["int", "uint", "float"]
int = ["i8", "i16", "i32", "i64", "i128", "isize"]
uint = ["u8", "u16", "u32", "u64", "u128", "usize"]
float = ["f32", "f64"]

i8    = []
i16   = []
i32   = []
i64   = []
i128  = []
isize = []

u8    = []
u16   = []
u32   = []
u64   = []
u128  = []
usize = []

f32   = []
f64   = []

bool  = []


[badges]
travis-ci = { repository = "icetemple/itconfig-rs" }
maintenance = { status = "actively-developed" }
